name: Full CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release (i.e.: 1.2.0)'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set Release Version ${{ github.event.inputs.release_version }}
        if: github.event_name == 'workflow_dispatch'
        run: |
          pip install --upgrade bumpversion
          bumpversion --new-version ${{ github.event.inputs.release_version }} patch

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run SonarQube Analysis
        if: contains(github.ref, 'main')
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL="${{ vars.LINTY_CLOUD_URL }}" \
            -e SONAR_TOKEN="${{ secrets.SONARQUBE_SCANNER_FOR_PRIVATE_REPOSITORIES_TOKEN }}" \
            -v "$PWD:/usr/src" \
            lintyservices/linty-scanner:latest \
            -Dsonar.projectKey=sonarqube-api \
            -Dsonar.projectName="SonarQube API"

      - name: Build Package
        run: |
          python3 -m pip install --upgrade build
          python3 -m build

      - name: Upload Package
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: sonarqube-*.tar.gz

      - name: Commit, Push and Tag Release Version ${{ github.event.inputs.release_version }}
        if: github.event_name == 'workflow_dispatch'
        uses: EndBug/add-and-commit@v9
        with:
          add: '*'
          author_name: GitHub Actions
          author_email: github-actions@linty-services.com
          message: Release version ${{ github.event.inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Commit Hash
        if: github.event_name == 'workflow_dispatch'
        run: echo "RELEASE_COMMIT=$(echo $(git rev-parse HEAD))" >> $GITHUB_ENV

      - name: "GitHub Release: ${{ github.event.inputs.release_version }}"
        if: github.event_name == 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_version }}
          artifacts: dist/sonarqube-*.tar.gz
          name: ${{ github.event.inputs.release_version }}
          commit: ${{ env.RELEASE_COMMIT }}